In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("sales_raw_500.xlsx")

In [ ]:
df

     Order_ID           Order_Date Customer Region  Product  Sales   Cost
0        1001            1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  2023-07-10 00:00:00     Aman   West   Laptop   8905   5593
2        1003  2023-05-11 00:00:00    Rahul  South  Monitor  59987  39959
3        1004            2/19/2024    Rahul  South  Printer  49597  33892
4        1005            1/26/2024   Anjali  North   Laptop  54797  34468
..        ...                  ...      ...    ...      ...    ...    ...
515      1389  2024-12-02 00:00:00    Vikas  North   Laptop  17924  12145
516      1496            4/24/2023    Kiran  North  Printer  23434  16388
517      1031            2/19/2023    Vikas   East  Printer  58883  43579
518      1317  2023-05-07 00:00:00     Aman  North   Laptop  76781  66865
519      1409            1/16/2024    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [ ]:
#remove_duplicates
df = df.drop_duplicates()
df

     Order_ID           Order_Date Customer Region  Product  Sales   Cost
0        1001            1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  2023-07-10 00:00:00     Aman   West   Laptop   8905   5593
2        1003  2023-05-11 00:00:00    Rahul  South  Monitor  59987  39959
3        1004            2/19/2024    Rahul  South  Printer  49597  33892
4        1005            1/26/2024   Anjali  North   Laptop  54797  34468
..        ...                  ...      ...    ...      ...    ...    ...
495      1496            4/24/2023    Kiran  North  Printer  23434  16388
496      1497            6/27/2023   Anjali  South   Laptop  49007  35970
497      1498  2023-08-05 00:00:00     Aman   East   Tablet  19160  15636
498      1499                  NaN    Pooja   West   Mobile  59266  44326
499      1500  2023-07-10 00:00:00    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [ ]:
#dealing with NA
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

In [ ]:
df=df.dropna(subset=['Order_Date'])

In [ ]:
df['Profit']=df['Sales']-df['Cost']
df['Year']=df['Order_Date'].dt.year
df['Month']=df['Order_Date'].dt.month

/tmp/ipykernel_1763/4291496937.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit']=df['Sales']-df['Cost']
/tmp/ipykernel_1763/4291496937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year']=df['Order_Date'].dt.year
/tmp/ipykernel_1763/4291496937.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month']=df['Order_Date'].dt.month

In [ ]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,3312,2023,7
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,20028,2023,5
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-08-05,Aman,East,Tablet,19160,15636,3524,2023,8
499,1500,2023-07-10,Vikas,North,Printer,34567,22426,12141,2023,7

In [ ]:
df.to_csv("sales_raw_500.csv",index=False)